python transform.py --score_path_regexp packaged-scores/chr1.all.scores  > chr1.out &
python transform.py --score_path_regexp packaged-scores/chr10.all.scores > chr10.out &
python transform.py --score_path_regexp packaged-scores/chr11.all.scores > chr11.out &
python transform.py --score_path_regexp packaged-scores/chr12.all.scores > chr12.out &
python transform.py --score_path_regexp packaged-scores/chr13.all.scores > chr13.out &
python transform.py --score_path_regexp packaged-scores/chr14.all.scores > chr14.out &
python transform.py --score_path_regexp packaged-scores/chr15.all.scores > chr15.out &
python transform.py --score_path_regexp packaged-scores/chr16.all.scores > chr16.out &
python transform.py --score_path_regexp packaged-scores/chr17.all.scores > chr17.out &
python transform.py --score_path_regexp packaged-scores/chr18.all.scores > chr18.out &
python transform.py --score_path_regexp packaged-scores/chr19.all.scores > chr19.out &
python transform.py --score_path_regexp packaged-scores/chr2.all.scores > chr2.out &
python transform.py --score_path_regexp packaged-scores/chr20.all.scores > chr20.out &
python transform.py --score_path_regexp packaged-scores/chr21.all.scores > chr21.out &
python transform.py --score_path_regexp packaged-scores/chr22.all.scores > chr22.out &
python transform.py --score_path_regexp packaged-scores/chr3.all.scores > chr3.out &
python transform.py --score_path_regexp packaged-scores/chr4.all.scores > chr4.out &
python transform.py --score_path_regexp packaged-scores/chr5.all.scores > chr5.out &
python transform.py --score_path_regexp packaged-scores/chr6.all.scores > chr6.out &
python transform.py --score_path_regexp packaged-scores/chr7.all.scores > chr7.out &
python transform.py --score_path_regexp packaged-scores/chr8.all.scores > chr8.out &
python transform.py --score_path_regexp packaged-scores/chr9.all.scores > chr9.out &
python transform.py --score_path_regexp packaged-scores/chrX.all.scores > chrX.out &
python transform.py --score_path_regexp packaged-scores/chrY.all.scores > chrY.out &
